mol_file_name : "tests/mol_83.mol"
exp_name: "mol_83_tmp_1"
spin_multiplicity : 1
charge : 0
orca_exec_command: "/opt/orca5/orca"
num_of_procs : 8
orca_method : "hf-3c cpcm(water)"
broken_struct_energy : 100.
bond_length_threshold : 0.7
rolling_window_size : 5
rolling_std_threshold : 0
rolling_mean_threshold : 0
num_initial_points : 1
max_steps : 1
acquisition_function : "ei"
